version: "3.9"

services:
  # ──────────────────────── Neo4j DB ───────────────────────
  neo4j:
    image: neo4j:5.18
    container_name: neo4j
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc","apoc-extended","n10s","graph-data-science"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,n10s.*,gds.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*,n10s.*,gds.*
      - NEO4J_dbms_transaction_timeout=300s
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data:rw
      - ./logs:/logs
      - ./plugins:/plugins
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'cypher-shell -a bolt://localhost:7687 -u ${NEO4J_USER} -p ${NEO4J_PASSWORD} "RETURN 1;"',
        ]
      interval: 20s
      timeout: 10s
      retries: 20
      start_period: 120s

  # ──────────────────── Streamlit Web-App ───────────────────
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wadi_streamlit
    ports:
      - "8501:8501"
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./data:/app/data
      - ./results:/app/results
      - ./test:/app/test
      - ./config:/app/config
      - ./templates:/app/templates
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped

volumes:
  neo4j_data:
  # (neo4j_plugins entfällt, da wir nun direkt Local Folder "neo4j/plugins" nutzen)
