feature_keys:
  - FeatureID
  - Category
  - Category2
  - Age
  - Condition
  - Height
  - Length
  - Width
  - Location1
  - Location2
  - X
  - Y
  - Lon
  - Lat
  - Rockart1
  - Rockart2
  - Rockart3
  - Rockart4
  - Rockart5
  - Rockart6
  - embedding
  - geometry

site_keys:
  - SiteID
  - Category
  - Surface
  - NoOfFeatures
  - Location1
  - Location2
  - X
  - Y
  - Lon
  - Lat
  - Shape_Area
  - Shape_Length
  - embedding
  - geometry

mobility_indicators:
  - shelter
  - stoneplace
  - camp site
  - fireplace
  - gravel platform

sedentary_indicators:
  - habitation site
  - hut
  - settlement

water_sources:
  - well

grave_indicators:
  - graves
  - grave
  - tumulus
  - box graves
  - cleft burial
  - dome grave

stone_indicators:
  - stone features
  - stonering
  - wall
  - concentration of stones

rockart_motifs:
  - geometrische Symbole
  - andere
  - antropomorphe Figuren (unbewaffnet)
  - astronomische Symbole
  - Kamele
  - Kamele ohne Reiter
  - Rinder andere

category_map:
  feature:
    - tumulus
    - stonering
    - gravel platform
    - concentration of stones
    - box grave
    - shelter
    - gravel feature
    - hut
    - cleft burial
    - rock art
    - campsite
    - ceramics
    - stoneplace
    - other
    - fireplace
    - alam
    - paved platform
    - platform
    - tethering stone
    - dome grave
    - deposit
    - stonefeature
    - wall
    - grave
    - lithics
    - workshop
    - stone feature
    - well
    - habitation site
    - settlement
    - gibla
    - surface finds
    - rock gong
    - stone ring
    - graves
  site:
    - graves
    - stone features
    - campsite
    - habitation site
    - other
    - surface finds
    - rock arts
    - well
    - big ruins
category2_map:
  feature:
    - all
    - graves
    - stone features
    - campsite
    - habitation site
    - other
    - surface finds
    - rock arts
    - ceramics
location_terms:
  feature:
    - terrace
    - ridge
    - slope
    - khor
    - plain
    - pathway
    - riparian
    - hinterland
    - dyke
    - plateau
    - hangfuss
    - pediment
    - riaprian
    - rdige
    - hinteralnd
    - rideg
    - pass
  site:
    - ridge
    - terrace
    - slope
    - khor
    - plain
    - pathway
    - riparian
    - hinterland
    - dyke
    - plateau
    - hangfuss
    - pediment
    - pass
location1_map:
  feature:
    - terrace
    - ridge
    - slope
    - plain
    - khor
    - riparian
    - pathway
    - hinterland
    - plateau
    - dyke
    - hangfuss
    - pediment
    - rdige
    - riaprian
    - rideg
    - pass
    - hinteralnd
  site:
    - ridge
    - terrace
    - slope
    - plain
    - khor
    - riparian
    - pathway
    - hinterland
    - plateau
    - dyke
    - hangfuss
    - pediment
    - pass
location2_map:
  feature:
    - khor
    - slope
    - pathway
    - terrace
    - ridge
    - hinterland
    - plain
    - dyke
    - riparian
    - plateau
    - hangfuss
    - hinteralnd
    - riaprian
    - pediment
  site:
    - khor
    - slope
    - pathway
    - terrace
    - ridge
    - plain
    - hinterland
    - dyke
    - riparian
    - plateau
    - hangfuss
    - pediment
