feature_keys:
  - FeatureID
  - Category
  - Category2
  - Age
  - Condition
  - Height
  - Length
  - Width
  - Location1
  - Location2
  - X
  - Y
  - Lon
  - Lat
  - Rockart1
  - Rockart2
  - Rockart3
  - Rockart4
  - Rockart5
  - Rockart6
  - embedding
  - geometry

site_keys:
  - SiteID
  - Category
  - Surface
  - NoOfFeatures
  - Location1
  - Location2
  - X
  - Y
  - Lon
  - Lat
  - Shape_Area
  - Shape_Length
  - embedding
  - geometry

mobility_indicators:
  - shelter
  - stoneplace
  - camp site
  - fireplace
  - gravel platform

sedentary_indicators:
  - habitation site
  - hut
  - settlement

water_sources:
  - well

rock_art_indicators:
  - rock art
  - RockArt1
  - RockArt2
  - RockArt3
  - RockArt4
  - RockArt5
  - RockArt6

grave_categories_site:
  - graves
  - tumulus
  - box graves
  - cleft burial
  - dome grave

grave_categories_feature:
  - grave

stone_features:
  - stone features
  - stonering
  - wall
  - concentration of stones

site_surface_types:
  - bare
  - partly overgrown
  - overgrown
  - campsite
  - unknown

location_terms:
  - ridge
  - slope
  - terrace
  - riparian
  - dyke
  - pathway
  - khor
  - plain
  - hinterland
  - Hangfuss
  - plateau
  - pediment

rockart_motifs:
  - geometrische Symbole
  - andere
  - antropomorphe Figuren (unbewaffnet)
  - astronomische Symbole
  - Kamele
  - Kamele ohne Reiter
  - Rinder andere

category_map:
  alam: Feature
  big ruins: Site
  box grave: Feature # box‑grave structures recorded as Features
  campsite: Both # appears in Features & Sites
  ceramics: Feature
  cleft burial: Feature
  concentration of stones: Feature
  deposit: Feature
  dome grave: Feature
  fireplace: Feature
  gibla: Feature
  grave: Feature
  gravel feature: Feature
  gravel platform: Feature
  graves: Both
  habitation site: Both
  hut: Feature
  lithics: Feature
  other: Both
  paved platform: Feature
  platform: Feature
  rock art: Feature
  rock gong: Feature
  settlement: Feature
  shelter: Feature
  stone feature: Feature
  stone features: Site
  stoneplace: Feature
  stone ring: Feature
  stonefeature: Feature
  stonering: Feature
  surface finds: Both
  tethering stone: Feature
  tumulus: Feature
  well: Both
  workshop: Feature

category2_map:
  all: Feature
  campsite: Feature
  ceramics: Feature
  graves: Feature
  habitation site: Feature
  other: Feature
  rock arts: Feature
  stone features: Feature
  surface finds: Feature

location1_map:
  Hangfuss: Both
  dyke: Both
  hangfuss: Both
  hinteralnd: Feature # rare typo
  hinterland: Both
  khor: Both
  pass: Both
  pathway: Both
  pediment: Both
  plain: Both
  plateau: Both
  rdige: Feature # rare typo
  rideg: Feature # rare typo
  ridge: Both
  riparian: Both
  slope: Both
  terrace: Both

location2_map:
  Hangfuss: Both
  dyke: Both
  hinteralnd: Feature
  hinterland: Both
  khor: Both
  pathway: Both
  pediment: Both
  plain: Both
  plateau: Both
  ridge: Both
  riaprian: Feature # rare typo
  riparian: Both
  slope: Both
  terrace: Both
